name: .NET Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4  # Updated to latest checkout version for consistency

    - name: Setup .NET
      uses: actions/setup-dotnet@v4  # Updated to latest setup-dotnet version
      with:
        dotnet-version: '6.0.x' # Match the .NET version for Emby plugins

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Upload build artifact
      uses: actions/upload-artifact@v4  # Upgraded to v4
      with:
        name: ViewCounterPlugin
        path: ViewCounter/bin/Release/**/*.dll
        # Optional: Add if your build includes hidden files
        # include-hidden-files: true
